In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Read the dataframe

In [4]:
df = pd.read_csv('face.csv')
df

0         1         2         3         4         5         6  \
0    0.309917  0.367769  0.417355  0.442149  0.528926  0.607438  0.657025   
1    0.454545  0.471074  0.512397  0.557851  0.595041  0.640496  0.681818   
2    0.318182  0.400826  0.491736  0.528926  0.586777  0.657025  0.681818   
3    0.198347  0.194215  0.194215  0.194215  0.190083  0.190083  0.243802   
4    0.500000  0.545455  0.582645  0.623967  0.648760  0.690083  0.694215   
..        ...       ...       ...       ...       ...       ...       ...   
395  0.400826  0.495868  0.570248  0.632231  0.648760  0.640496  0.661157   
396  0.367769  0.367769  0.351240  0.301653  0.247934  0.247934  0.367769   
397  0.500000  0.533058  0.607438  0.628099  0.657025  0.632231  0.657025   
398  0.214876  0.219008  0.219008  0.223140  0.210744  0.202479  0.276859   
399  0.516529  0.462810  0.280992  0.252066  0.247934  0.367769  0.574380   

            7         8         9  ...      4087      4088      4089  \
0    0.677686  0.690083  0.685950  ...  0.669422  0.652893  0.661157   
1    0.702479  0.710744  0.702479  ...  0.157025  0.136364  0.148760   
2    0.685950  0.702479  0.698347  ...  0.132231  0.181818  0.136364   
3    0.404959  0.483471  0.516529  ...  0.636364  0.657025  0.685950   
4    0.714876  0.723140  0.731405  ...  0.161157  0.177686  0.173554   
..        ...       ...       ...  ...       ...       ...       ...   
395  0.636364  0.665289  0.698347  ...  0.396694  0.264463  0.099174   
396  0.512397  0.574380  0.628099  ...  0.334711  0.289256  0.285124   
397  0.669422  0.673554  0.702479  ...  0.148760  0.152893  0.161157   
398  0.400826  0.487603  0.549587  ...  0.392562  0.367769  0.409091   
399  0.615702  0.661157  0.615702  ...  0.264463  0.293388  0.301653   

         4090      4091      4092      4093      4094      4095  target  
0    0.475207  0.132231  0.148760  0.152893  0.161157  0.157025       0  
1    0.152893  0.152893  0.152893  0.152893  0.152893  0.152893       0  
2    0.128099  0.148760  0.144628  0.140496  0.148760  0.152893       0  
3    0.727273  0.743802  0.764463  0.752066  0.752066  0.739669       0  
4    0.177686  0.177686  0.177686  0.177686  0.173554  0.173554       0  
..        ...       ...       ...       ...       ...       ...     ...  
395  0.181818  0.243802  0.247934  0.161157  0.157025  0.136364      39  
396  0.338843  0.404959  0.458678  0.487603  0.512397  0.549587      39  
397  0.161157  0.173554  0.157025  0.177686  0.148760  0.190083      39  
398  0.479339  0.524793  0.545455  0.574380  0.590909  0.603306      39  
399  0.293388  0.322314  0.322314  0.359504  0.355372  0.384298      39  

[400 rows x 4097 columns]

### Divide the features and target variables

In [5]:
X = df.drop('target', axis = 1)
y = df['target']

### Define the final required dimension count

In [56]:
# Define the number of dimensions (d) and the desired reduced dimensionality (d')
d = X.shape[1]  # 128 dimensions
d_prime = 123 # You can change this value based on your requirements

### Seperate the data into train and test samples

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [58]:
X_train = X_train.to_numpy()
y_train = y_train.to_numpy()
X_test = X_test.to_numpy()
y_test = y_test.to_numpy()

### Compute Mean Vectors for each class

In [59]:
class_means = []
for class_label in range(40):
    mean_class = np.mean(X_train[y_train == class_label, :], axis=0)
    class_means.append(mean_class)
class_means

[array([0.34238489, 0.36953956, 0.3996458 , ..., 0.32408501, 0.32762693,
        0.32467533]),
 array([0.62258954, 0.64508725, 0.67860424, ..., 0.13452709, 0.11248852,
        0.10927456]),
 array([0.40436836, 0.42384888, 0.4557261 , ..., 0.26033058, 0.24498229,
        0.24380165]),
 array([0.45919422, 0.48037191, 0.47055786, ..., 0.30785124, 0.28822314,
        0.2732438 ]),
 array([0.52324382, 0.53254134, 0.57024796, ..., 0.42252066, 0.40650827,
        0.40082645]),
 array([0.57024792, 0.59142562, 0.63326448, ..., 0.65754132, 0.6089876 ,
        0.59349173]),
 array([0.23507805, 0.25344353, 0.31359045, ..., 0.33103764, 0.27731864,
        0.24839302]),
 array([0.42097108, 0.45661156, 0.51033057, ..., 0.23708677, 0.25      ,
        0.25516529]),
 array([0.3989899 , 0.4164371 , 0.43709826, ..., 0.33884297, 0.35261707,
        0.3516988 ]),
 array([0.43270367, 0.51948051, 0.56965763, ..., 0.09504132, 0.11570248,
        0.12396694]),
 array([0.35261708, 0.38360882, 0.50413223, ..., 0

### Within Class Scatter Matrix

In [60]:
S_W = np.zeros((d, d))  # Initialize the within-class scatter matrix

for class_label, mean_class in enumerate(class_means):
    scatter_class = np.zeros((d, d))
    class_samples = X_train[y_train == class_label]

    for x in class_samples:
        x_minus_mean = x - mean_class
        scatter_class += np.outer(x_minus_mean, x_minus_mean)

    S_W += scatter_class

In [61]:
S_W

array([[ 5.52177666,  5.23619723,  4.31917069, ..., -0.79170999,
        -0.82734918, -0.67134082],
       [ 5.23619723,  5.67692287,  5.13950313, ..., -1.15154156,
        -1.0586106 , -0.89364125],
       [ 4.31917069,  5.13950313,  5.89595879, ..., -1.49365327,
        -1.34293714, -1.21662807],
       ...,
       [-0.79170999, -1.15154156, -1.49365327, ...,  5.90185227,
         4.851215  ,  4.08599263],
       [-0.82734918, -1.0586106 , -1.34293714, ...,  4.851215  ,
         5.44230423,  4.9174225 ],
       [-0.67134082, -0.89364125, -1.21662807, ...,  4.08599263,
         4.9174225 ,  5.26384662]])

### Between Class Scatter Matrix

In [62]:
mean_overall = np.mean(X_train, axis=0)
S_B = np.zeros((d, d))  # Initialize the between-class scatter matrix

for class_label, mean_class in enumerate(class_means):
    count_class = len(X_train[y_train == class_label])
    mean_minus_overall = mean_class - mean_overall
    scatter_class = count_class * np.outer(mean_minus_overall, mean_minus_overall)
    S_B += scatter_class

In [63]:
S_B

array([[ 4.99012472,  5.19326258,  5.00899934, ..., -1.07224146,
        -0.86173412, -0.65525069],
       [ 5.19326258,  5.70055755,  5.69466884, ..., -1.5067041 ,
        -1.2959715 , -1.03080143],
       [ 5.00899934,  5.69466884,  6.13641619, ..., -2.19310874,
        -1.95521764, -1.6280637 ],
       ...,
       [-1.07224146, -1.5067041 , -2.19310874, ...,  5.9036222 ,
         5.48182075,  5.18168509],
       [-0.86173412, -1.2959715 , -1.95521764, ...,  5.48182075,
         5.31850365,  5.10642768],
       [-0.65525069, -1.03080143, -1.6280637 , ...,  5.18168509,
         5.10642768,  5.1047885 ]])

### Eigen Values and Eigen Vectors

In [64]:
# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(np.linalg.inv(S_W).dot(S_B))

# Sort the eigenvalues and eigenvectors
eigen_pairs = [(eigenvalues[i], eigenvectors[:, i]) for i in range(len(eigenvalues))]
eigen_pairs = sorted(eigen_pairs, key=lambda x: x[0], reverse=True)

# Choose the top d' eigenvectors and create the transformation matrix W
W = np.array([eigen_pair[1] for eigen_pair in eigen_pairs[:d_prime]]).T

### Get the final dataframe with d' dimensions

In [65]:
# Project the data onto the reduced-dimensional space
X_train_lda = X_train.dot(W)
X_test_lda = X_test.dot(W)

In [66]:
X_train_lda

array([[ 0.04765798+0.02610457j,  0.04765798-0.02610457j,
        -0.04285459+0.01391231j, ...,  0.08226804+0.00902948j,
         0.08226804-0.00902948j, -0.01518085+0.07426844j],
       [ 0.04990537+0.0359784j ,  0.04990537-0.0359784j ,
        -0.04938392+0.00989909j, ...,  0.04275148+0.0421957j ,
         0.04275148-0.0421957j , -0.03013558+0.11980068j],
       [ 0.00529888+0.00651607j,  0.00529888-0.00651607j,
        -0.04002194+0.03432614j, ...,  0.051594  +0.09025391j,
         0.051594  -0.09025391j, -0.04587822+0.12546701j],
       ...,
       [ 0.06480595+0.02460348j,  0.06480595-0.02460348j,
        -0.03693622+0.00611584j, ...,  0.08041942-0.00444794j,
         0.08041942+0.00444794j,  0.02970637+0.0774124j ],
       [ 0.02987141+0.02934122j,  0.02987141-0.02934122j,
        -0.05746182+0.01120071j, ...,  0.01062791-0.06852716j,
         0.01062791+0.06852716j, -0.01428296-0.01882141j],
       [-0.00264474+0.00737973j, -0.00264474-0.00737973j,
        -0.05823055+0.01725261

In [67]:
X_test_lda

array([[ 0.06038572+0.01529328j,  0.06038572-0.01529328j,
         0.00154758+0.00712971j, ...,  0.06848456+0.04294506j,
         0.06848456-0.04294506j, -0.02008284+0.08070894j],
       [-0.03008137+0.03287601j, -0.03008137-0.03287601j,
        -0.04779836+0.07229391j, ...,  0.11346198+0.07484227j,
         0.11346198-0.07484227j, -0.03378676+0.12091439j],
       [ 0.0755044 -0.00387688j,  0.0755044 +0.00387688j,
        -0.03038024+0.0045076j , ...,  0.12613279-0.07155914j,
         0.12613279+0.07155914j,  0.00903928+0.01716969j],
       ...,
       [ 0.06108131+0.02381683j,  0.06108131-0.02381683j,
        -0.02669957+0.02865511j, ...,  0.05265464+0.1023625j ,
         0.05265464-0.1023625j , -0.08457658+0.11829983j],
       [ 0.03880013+0.03884968j,  0.03880013-0.03884968j,
        -0.07099539+0.04583249j, ..., -0.00779311-0.02292228j,
        -0.00779311+0.02292228j, -0.06736094+0.06418937j],
       [ 0.08475896+0.04539482j,  0.08475896-0.04539482j,
        -0.06252963+0.02263021

### We will be using KNN Classifier for modelling

#### Euclidean Distance Function

In [26]:
def euclidean(X_train, X_test):
    all_point_distances = []
    for i in X_test:
        point_distance = []
        for j in X_train:
            dist = np.sqrt(np.sum((j-i)**2))
            point_distance.append(dist)
        all_point_distances.append(point_distance)
    arr = np.array(all_point_distances)
    return arr

#### KNN Model Function

In [27]:
def knn_classify(distance_array, y_train, k):
    array_indexes = []
    for point in distance_array:
        nearest_points = np.argsort(point)[:k]
        array_indexes.append(nearest_points)
    array_indexes = np.array(array_indexes)
    
    y_values = []
    for point in array_indexes:
        values = []
        for i in point:
            values.append(y_train[i])
        y_values.append(values)
    y_pred = []
    for point in y_values:
        y_pred.append(max(point, key = point.count))
    y_pred = np.array(y_pred)
    return y_pred

In [76]:
def check_accuracy(y_pred, y_test):
    return (np.sum(y_pred == y_test) / len(y_test))*10

In [75]:
eud = euclidean(X_train_lda, X_test_lda)
k = 3
y_pred = knn_classify(eud, y_train, k)
print(f"Actual Output: {y_test}\nPredicted Output: {y_pred}")

Actual Output: [15 28 18 11 27 18 10 10 30 31 25  2 15 13 11 18 24 30 37  9 10 25 10  4
 34  2 24  6 23 33  3  5 14  1 32 18 33  2 29 11 11 34 15 38 32 33 13 25
  4 12 39 21 35 39  5  0 29 13 19  0 22 34 29  3 21 22  0 23 14  7 19  9
 24 34 20 27 33  9  7  8]
Predicted Output: [ 8  6 18 33 35 30 12 35 13  3 23 37  6 18 10 19  9 24 35 36 12 12 17  3
 16  1 30 26 31  5  2 27 14 18 38 19  3 33 30 33 23 16  4  9  4 30 37 35
 32  2 34  3 28  4 27  7 30  3 14 33  3 24 30 16  8  3 13  3 37 24 31  2
 26 17 36 26  3 19  3  1]


In [78]:
print(f"Accuracy with k={k} : {check_accuracy(y_pred, y_test)*100}%")

Accuracy with k=3 : 25.0%
